version: '3.9'

services:
  app:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLIENTVAR=clientvar
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
    ports:
      - 3000:3000
