version: '3.9'

services:
  app:
    hostname: app-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspaces/app-web:cached
      - app-web-bashhistory:/commandhistory
      - .p10k.zsh:/.p10k.zsh:cached
    ports:
      - 3000:3000
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:15.2-alpine3.17
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d dev']
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - 5432:5432
    command: ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']

  cache:
    image: redis:7.0.9-alpine3.17
    restart: always
    environment:
      - maxmemory-policy=noeviction
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 1s
      retries: 30

  mailcatcher:
    restart: always
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1080:1080

  # TODO - Add local unleash server

volumes:
  db_data:
    driver: local
  app-web-bashhistory:
    driver: local
